server:
  port: 8080

jsonPlaceHolder:
  apiAddress: "https://jsonplaceholder.typicode.com/"

#graphql:
#  servlet:
#    enabled: true
#    mapping: /graphql
#    corsEnabled: false
#    cors:
#      allowed-origins: http://localhost:8080
#      allowed-methods: POST
#    exception-handlers-enabled: true
#    context-setting: PER_REQUEST_WITH_INSTRUMENTATION
#    async-mode-enabled: true
#  tools:
#    schema-location-pattern: "**/*.graphqls"
#    introspection-enabled: true
